spring:
  application:
    name: ai-code-helper
  profiles:
    active: local
langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: sk-c0d68a323a844b9d8ae24fc18fc45d2e
        model-name: qwen-plus