spring:
  application:
    name: ai-code-helper
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-plus
      embedding-model:
        model-name : text-embedding-v4